name = "drive"
type = "webpack"
workers_dev = true
account_id = "f9778f6dbfb17565954f0a8d26999d47"
zone_id = "956a07792085c07bc7e4f0aac1dc3378"
kv_namespaces = [
    { binding = "BUCKET", id = "6bc7d097a8484b4cb11636dd80969e3d", preview_id = "b034ff854c4346ccb7238710e3ddeba3" }
]

[env.staging]
name = "drive-staging"
